spring:
  datasource:
    url: jdbc:mysql://localhost/mini_blog?serverTimezone=JST
    username: root
    password:
  session:
    store-type: jdbc

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

